namespace Titan.Library.Application;

public static class ApplicationMessageKeys
{
    public const string NO_VALIDATION_ERROR = nameof(NO_VALIDATION_ERROR);

    // Books
    public const string BOOK_ISBN_SHOULD_NOT_BE_EMPTY = nameof(BOOK_ISBN_SHOULD_NOT_BE_EMPTY);
    public const string BOOK_TITLE_SHOULD_NOT_BE_EMPTY = nameof(BOOK_TITLE_SHOULD_NOT_BE_EMPTY);
    public const string INVALIDE_AUTHOR_ID = nameof(INVALIDE_AUTHOR_ID);
    public const string BOOK_CREATED_SUCCESSFULLY = nameof(BOOK_CREATED_SUCCESSFULLY);
    public const string BOOKS_LIST_RETREIVED_SUCCESSFULLY = nameof(BOOKS_LIST_RETREIVED_SUCCESSFULLY);
    public const string BOOK_NOT_FOUND = nameof(BOOK_NOT_FOUND);
    public const string BOOK_UPDATED_SUCCESSFULLY = nameof(BOOK_UPDATED_SUCCESSFULLY);
    public const string BOOK_DELETED_SUCCESSFULLY = nameof(BOOK_DELETED_SUCCESSFULLY);
    public const string BOOK_RETRIEVED_SUCCESSFULLY = nameof(BOOK_RETRIEVED_SUCCESSFULLY);
    public const string BOOKS_BY_AUTHOR_RETRIEVED_SUCCESSFULLY = nameof(BOOKS_BY_AUTHOR_RETRIEVED_SUCCESSFULLY);
    public const string BOOK_STOCK_ADDED_SUCCESSFULLY = nameof(BOOK_STOCK_ADDED_SUCCESSFULLY);
    public const string STOCK_AMOUNT_MUST_BE_POSITIVE = nameof(STOCK_AMOUNT_MUST_BE_POSITIVE);

    // Authors
    public const string AUTHOR_NAME_REQUIRED = nameof(AUTHOR_NAME_REQUIRED);
    public const string AUTHOR_EMAIL_REQUIRED = nameof(AUTHOR_EMAIL_REQUIRED);
    public const string AUTHOR_PASSWORD_REQUIRED = nameof(AUTHOR_PASSWORD_REQUIRED);
    public const string AUTHOR_CREATED_SUCCESSFULLY = nameof(AUTHOR_CREATED_SUCCESSFULLY);
    public const string AUTHORS_RETRIEVED_SUCCESSFULLY = nameof(AUTHORS_RETRIEVED_SUCCESSFULLY);
    public const string AUTHOR_RETRIEVED_SUCCESSFULLY = nameof(AUTHOR_RETRIEVED_SUCCESSFULLY);
    public const string AUTHOR_NOT_FOUND = nameof(AUTHOR_NOT_FOUND);
    public const string AUTHOR_DELETED_SUCCESSFULLY = nameof(AUTHOR_DELETED_SUCCESSFULLY);

    // Customers
    public const string CUSTOMER_NAME_REQUIRED = nameof(CUSTOMER_NAME_REQUIRED);
    public const string CUSTOMER_EMAIL_REQUIRED = nameof(CUSTOMER_EMAIL_REQUIRED);
    public const string CUSTOMER_PASSWORD_REQUIRED = nameof(CUSTOMER_PASSWORD_REQUIRED);
    public const string CUSTOMER_CREATED_SUCCESSFULLY = nameof(CUSTOMER_CREATED_SUCCESSFULLY);
    public const string CUSTOMERS_RETRIEVED_SUCCESSFULLY = nameof(CUSTOMERS_RETRIEVED_SUCCESSFULLY);
    public const string CUSTOMER_RETRIEVED_SUCCESSFULLY = nameof(CUSTOMER_RETRIEVED_SUCCESSFULLY);
    public const string CUSTOMER_NOT_FOUND = nameof(CUSTOMER_NOT_FOUND);
    public const string CUSTOMER_DELETED_SUCCESSFULLY = nameof(CUSTOMER_DELETED_SUCCESSFULLY);

    // Borrows
    public const string BOOK_NOT_AVAILABLE = nameof(BOOK_NOT_AVAILABLE);
    public const string CUSTOMER_NOT_FOUND_FOR_BORROW = nameof(CUSTOMER_NOT_FOUND_FOR_BORROW);
    public const string BOOK_ALREADY_BORROWED_BY_CUSTOMER = nameof(BOOK_ALREADY_BORROWED_BY_CUSTOMER);
    public const string BORROW_CREATED_SUCCESSFULLY = nameof(BORROW_CREATED_SUCCESSFULLY);
    public const string BORROW_NOT_FOUND = nameof(BORROW_NOT_FOUND);
    public const string BOOK_ALREADY_RETURNED = nameof(BOOK_ALREADY_RETURNED);
    public const string BOOK_RETURNED_SUCCESSFULLY = nameof(BOOK_RETURNED_SUCCESSFULLY);
    public const string BORROWS_RETRIEVED_SUCCESSFULLY = nameof(BORROWS_RETRIEVED_SUCCESSFULLY);
    public const string CUSTOMER_BORROWS_RETRIEVED_SUCCESSFULLY = nameof(CUSTOMER_BORROWS_RETRIEVED_SUCCESSFULLY);

    // Messages
    public const string MESSAGE_KEY_REQUIRED = nameof(MESSAGE_KEY_REQUIRED);
    public const string MESSAGE_VALUE_REQUIRED = nameof(MESSAGE_VALUE_REQUIRED);
    public const string MESSAGE_CREATED_SUCCESSFULLY = nameof(MESSAGE_CREATED_SUCCESSFULLY);
    public const string MESSAGE_UPDATED_SUCCESSFULLY = nameof(MESSAGE_UPDATED_SUCCESSFULLY);
    public const string MESSAGE_DELETED_SUCCESSFULLY = nameof(MESSAGE_DELETED_SUCCESSFULLY);
    public const string MESSAGE_NOT_FOUND = nameof(MESSAGE_NOT_FOUND);
    public const string MESSAGES_RETRIEVED_SUCCESSFULLY = nameof(MESSAGES_RETRIEVED_SUCCESSFULLY);
    public const string MESSAGE_RETRIEVED_SUCCESSFULLY = nameof(MESSAGE_RETRIEVED_SUCCESSFULLY);

    // Cache
    public const string CACHE_BOOKS_RETRIEVED_SUCCESSFULLY = nameof(CACHE_BOOKS_RETRIEVED_SUCCESSFULLY);
    public const string CACHE_REFRESHED_SUCCESSFULLY = nameof(CACHE_REFRESHED_SUCCESSFULLY);
    public const string CACHE_RECORD_CREATED_SUCCESSFULLY = nameof(CACHE_RECORD_CREATED_SUCCESSFULLY);
    public const string CACHE_RECORDS_RETRIEVED_SUCCESSFULLY = nameof(CACHE_RECORDS_RETRIEVED_SUCCESSFULLY);
}